# Generated by Django 4.2.5 on 2023-09-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("email", models.CharField(max_length=50, null=True)),
                ("mobileNo", models.CharField(max_length=10, null=True)),
                ("password", models.CharField(max_length=20, null=True)),
                ("address", models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
