# Generated by Django 4.2.5 on 2023-10-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pname", models.CharField(max_length=50, null=True)),
                ("price", models.FloatField()),
                ("description", models.CharField(max_length=500, null=True)),
                ("status", models.CharField(max_length=50, null=True)),
                ("quantity", models.IntegerField()),
                ("category", models.CharField(max_length=100, null=True)),
                ("created_at", models.DateTimeField()),
            ],
        ),
    ]
