# Generated by Django 4.2.5 on 2023-10-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="imgUrl",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
