# Generated by Django 4.2.5 on 2023-10-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_product_imgurl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="imgUrl",
        ),
    ]
