# Generated by Django 4.2.5 on 2023-10-02 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_product_created_at_remove_product_imgurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="product",
            name="imgUrl",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
