# Generated by Django 4.2.5 on 2023-10-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_product_created_at_product_imgurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
