# Generated by Django 4.2.5 on 2023-10-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_productimages_image1_productimages_image2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="imgUrl",
        ),
        migrations.AddField(
            model_name="product",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image4",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
