# Generated by Django 4.2.5 on 2023-10-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_product_imgurl_product_image1_product_image2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pname", models.CharField(max_length=50, null=True)),
                ("quantity", models.CharField(max_length=50, null=True)),
                ("price", models.CharField(max_length=50, null=True)),
                ("total", models.CharField(max_length=500, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="cart/")),
            ],
        ),
        migrations.DeleteModel(
            name="ProductImages",
        ),
    ]
